config/routes.rb
Rails.application.routes.draw do
  resources :projects

  resources :fundraisers

end

app/models/fundraiser.rb
class Fundraiser < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fundraisers_controller.rb
class FundraisersController < ApplicationController
  before_action :set_fundraiser, only: [:show, :edit, :update, :destroy]

  # GET /fundraisers
  # GET /fundraisers.json
  def index
    @fundraisers = Fundraiser.all
  end

  # GET /fundraisers/1
  # GET /fundraisers/1.json
  def show
  end

  # GET /fundraisers/new
  def new
    @fundraiser = Fundraiser.new
  end

  # GET /fundraisers/1/edit
  def edit
  end

  # POST /fundraisers
  # POST /fundraisers.json
  def create
    @fundraiser = Fundraiser.new(fundraiser_params)

    respond_to do |format|
      if @fundraiser.save
        format.html { redirect_to @fundraiser, notice: 'Fundraiser was successfully created.' }
        format.json { render :show, status: :created, location: @fundraiser }
      else
        format.html { render :new }
        format.json { render json: @fundraiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fundraisers/1
  # PATCH/PUT /fundraisers/1.json
  def update
    respond_to do |format|
      if @fundraiser.update(fundraiser_params)
        format.html { redirect_to @fundraiser, notice: 'Fundraiser was successfully updated.' }
        format.json { render :show, status: :ok, location: @fundraiser }
      else
        format.html { render :edit }
        format.json { render json: @fundraiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fundraisers/1
  # DELETE /fundraisers/1.json
  def destroy
    @fundraiser.destroy
    respond_to do |format|
      format.html { redirect_to fundraisers_url, notice: 'Fundraiser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fundraiser
      @fundraiser = Fundraiser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fundraiser_params
      params.require(:fundraiser).permit(:name, :email, :description)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:story, :target_amount, :amount_raised, :timeline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fundraisers_helper.rb
module FundraisersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/fundraisers/_form.html.erb
<%= form_for(@fundraiser) do |f| %>
  <% if @fundraiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fundraiser.errors.count, "error") %> prohibited this fundraiser from being saved:</h2>

      <ul>
      <% @fundraiser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>  
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>Welcome Akwaaba</div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fundraisers/edit.html.erb
<h1>Editing fundraiser</h1>

<%= render 'form' %>

<%= link_to 'Show', @fundraiser %> |
<%= link_to 'Back', fundraisers_path %>

app/views/fundraisers/index.html.erb
<h1>Listing fundraisers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fundraisers.each do |fundraiser| %>
      <tr>
        <td><%= fundraiser.name %></td>
        <td><%= fundraiser.email %></td>
        <td><%= fundraiser.description %></td>
        <td><%= link_to 'Show', fundraiser %></td>
        <td><%= link_to 'Edit', edit_fundraiser_path(fundraiser) %></td>
        <td><%= link_to 'Destroy', fundraiser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fundraiser', new_fundraiser_path %>

app/views/fundraisers/new.html.erb
<h1>New fundraiser</h1>

<%= render 'form' %>

<%= link_to 'Back', fundraisers_path %>

app/views/fundraisers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fundraiser.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @fundraiser.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fundraiser.description %>
</p>

<%= link_to 'Edit', edit_fundraiser_path(@fundraiser) %> |
<%= link_to 'Back', fundraisers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helperorg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>


  </div>
  <div class="field">
    <%= f.label :story %><br>
    <%= f.text_area :story %>
  </div>
  <div class="field">
    <%= f.label :target_amount %><br>
    <%= f.number_field :target_amount %>
  </div>
  <div class="field">
    <%= f.label :amount_raised %><br>
    <%= f.number_field :amount_raised %>
  </div>
  <div class="field">
    <%= f.label :timeline %><br>
    <%= f.date_select :timeline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Story</th>
      <th>Target amount</th>
      <th>Amount raised</th>
      <th>Timeline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.story %></td>
        <td><%= project.target_amount %></td>
        <td><%= project.amount_raised %></td>
        <td><%= project.timeline %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Story:</strong>
  <%= @project.story %>
</p>

<p>
  <strong>Target amount:</strong>
  <%= @project.target_amount %>
</p>

<p>
  <strong>Amount raised:</strong>
  <%= @project.amount_raised %>
</p>

<p>
  <strong>Timeline:</strong>
  <%= @project.timeline %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>